### PR TITLE
Added the comment funtcion

### LINKED ISSUE #43: [Comments] There is no populated author fields that is needed when getting comments
**Description:** There is no populated author fields that is needed when getting comments.

**Reproducible:** always.

**Preconditions:**
The user is logged in.

**Steps to reproduce:**
1. Create a comment

**Actual result:**

Image

**Expected result:**
Image

### PR DESCRIPTION
**Pull request by holus-bolus**
image
I recreated the post adding endpoint and added new functions
image
the add coment function expects certain comment structure, so it had to be created

### CODE REVIEW

**Review by vlad-khrychov — CHANGES_REQUESTED** [review]
This function is already in `develop` branch? Because this PR looks a little strange. There is only deleting of empty rows.

**Comment by holus-bolus** [comment]
> This function is already in `develop` branch? Because this PR looks a little strange. There is only deleting of empty rows.

No, it's waiting for the final review

**Comment by vlad-khrychov** [comment]
> > This function is already in `develop` branch? Because this PR looks a little strange. There is only deleting of empty rows.
> 
> No, it's waiting for the final review

I can see only this changes 
image

**Comment by holus-bolus** [comment]
> > > This function is already in `develop` branch? Because this PR looks a little strange. There is only deleting of empty rows.
> > 
> > 
> > No, it's waiting for the final review
> 
> I can see only this changes image

It is strange
image

As I understand it is on the required branch

**Review by online-marathon — APPROVED** [review]

**Pull request merged**
